CREATE TABLE EMPLOYEES (
    ID VARCHAR2(64) PRIMARY KEY,
    NAME VARCHAR2(255) NOT NULL,
    ROLE VARCHAR2(255),
    PHONE VARCHAR2(50),
    BASE_SALARY NUMBER(12, 2) DEFAULT 0,
    DEFAULT_MODE VARCHAR2(50) DEFAULT 'Cash',
    CREATED_AT VARCHAR2(64)
);

CREATE TABLE TRANSACTIONS (
    ID VARCHAR2(64) PRIMARY KEY,
    EMPLOYEE_ID VARCHAR2(64) NOT NULL,
    TX_TYPE VARCHAR2(50) NOT NULL,
    AMOUNT NUMBER(12, 2) NOT NULL,
    TX_DATE VARCHAR2(20) NOT NULL,
    PAYMENT_MODE VARCHAR2(50) NOT NULL,
    NOTE VARCHAR2(500),
    SALARY_MONTH NUMBER(2),
    SALARY_YEAR NUMBER(4),
    CREATED_AT VARCHAR2(64),
    CONSTRAINT FK_EMP_TX FOREIGN KEY (EMPLOYEE_ID) REFERENCES EMPLOYEES(ID) ON DELETE CASCADE
);

CREATE INDEX IDX_TX_EMP ON TRANSACTIONS(EMPLOYEE_ID);
CREATE INDEX IDX_TX_PERIOD ON TRANSACTIONS(EMPLOYEE_ID, TX_TYPE, SALARY_YEAR, SALARY_MONTH);